
CREATE TABLE IF NOT EXISTS conversations(
    id VARCHAR(255) PRIMARY KEY  DEFAULT (UUID()),
    is_group BOOLEAN NOT NULL DEFAULT FALSE,
    name VARCHAR(255) NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
); 